// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebArsip.Infrastructure.DbContexts;

#nullable disable

namespace WebArsip.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250909133630_SeedingDataPermissionPertama")]
    partial class SeedingDataPermissionPertama
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebArsip.Core.Entities.Archive", b =>
                {
                    b.Property<int>("ArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchiveId"));

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocId")
                        .HasColumnType("int");

                    b.HasKey("ArchiveId");

                    b.HasIndex("DocId")
                        .IsUnique();

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("WebArsip.Core.Entities.Document", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            DocId = 1,
                            CreatedDate = new DateTime(2025, 9, 9, 13, 36, 29, 887, DateTimeKind.Utc).AddTicks(4433),
                            Description = "Dokumen contoh awal untuk permission",
                            FilePath = "/uploads/docs/sample.pdf",
                            Status = "Active",
                            Title = "Panduan Arsip Awal"
                        });
                });

            modelBuilder.Entity("WebArsip.Core.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDownload")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpload")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<int>("DocId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId");

                    b.HasIndex("DocId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CanDelete = true,
                            CanDownload = true,
                            CanEdit = true,
                            CanUpload = true,
                            CanView = true,
                            DocId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 2,
                            CanDelete = true,
                            CanDownload = false,
                            CanEdit = true,
                            CanUpload = true,
                            CanView = true,
                            DocId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 3,
                            CanDelete = false,
                            CanDownload = true,
                            CanEdit = false,
                            CanUpload = false,
                            CanView = true,
                            DocId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 4,
                            CanDelete = false,
                            CanDownload = false,
                            CanEdit = true,
                            CanUpload = true,
                            CanView = true,
                            DocId = 1,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("WebArsip.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Compliance"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Audit"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Policy"
                        });
                });

            modelBuilder.Entity("WebArsip.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@company.com",
                            Name = "Administrator",
                            Password = "admin123",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("WebArsip.Core.Entities.Archive", b =>
                {
                    b.HasOne("WebArsip.Core.Entities.Document", "Document")
                        .WithOne("Archive")
                        .HasForeignKey("WebArsip.Core.Entities.Archive", "DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WebArsip.Core.Entities.Permission", b =>
                {
                    b.HasOne("WebArsip.Core.Entities.Document", "Document")
                        .WithMany("Permissions")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebArsip.Core.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebArsip.Core.Entities.User", b =>
                {
                    b.HasOne("WebArsip.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebArsip.Core.Entities.Document", b =>
                {
                    b.Navigation("Archive");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("WebArsip.Core.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
